### ISSUE TITLE
:disabled="disabled" not working

### ISSUE THREAD

**Issue by Ronak-maker** [baianat/verte#73]
not able to disable color picker

**Comment by ShetlandJ** [comment]
Here is our solution (stripped back for example):

```html
    <div :class="{'disabled': isDisabled}">
        <verte /> 
    </div>
```

```css
.disabled {
    pointer-events: none;
}
```
